### PR TITLE
db:finish task and dbFinish event

### PR DESCRIPTION
**Pull request by diggy**
This PR implements a `db:finish` task and a `dbFinish` event, in analogy to `shipit-deploy`.

### CODE REVIEW

**Comment by timkelty** [comment]
Looks good, thanks!

**Comment by timkelty** [comment]
Released with 1.8.0

**Comment by diggy** [comment]
Great! BTW, I was thinking `shipit-db` might also benefit from `dbPush` and `dbPull` events (cf. `shipit-assets`), but not really sure how/where to implement these.

**Comment by timkelty** [comment]
Yeah, across the board events need to be reworked and standardized.

Working on shipit 2.0 which will use gulpjs/undertaker for tasks, so I haven't worried about it too much.

**Pull request merged**
